spring.application.name=provajwt

# Configuração do Banco de Dados em Memória (H2)
spring.datasource.url=jdbc:h2:mem:helpdeskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar Console Web do H2 para Testes
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Configuração do Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Execução do script data.sql ao iniciar a aplicação
spring.sql.init.mode=always

# Configurações do Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# Parâmetros Customizados do JWT (Security)
jwt.secret= xxxxxx
jwt.expiration=xxxxx
